jobs:
  deploy-app-3:
    executor: node
    resource_class: medium
    steps:
      - echo "Deploying App 3"

workflows:
  docker_build_and_deploy:
    jobs:
      - deploy-app-3:
          requires:
            - nx-run
