jobs:
  deploy-app-1:
    executor: node
    resource_class: medium
    steps:
      - echo "Deploying App 1"

workflows:
  docker_build_and_deploy:
    jobs:
      - deploy-app-1:
          requires:
            - nx-run
